apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosy-landing-page
  namespace: cosy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: cosy-docs.jannekeipert.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cosy-landing-page
                port:
                  number: 80
  tls:
    - hosts:
        - cosy-docs.jannekeipert.de
      secretName: multi-domain-cert
