apiVersion: v1
kind: Service
metadata:
  name: cosy-landing-page
  namespace: cosy
spec:
  selector:
    app: cosy-landing-page
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
